version: "3.9"

services:
  node_db:
    container_name: node_db
    build: .
    image: onderi/node_sequelize_app
    ports:
      - "3001:3001"
    environment:
      - PG_DB=node
      - PG_USER=root
      - PG_PASSWORD=0909
      - PG_HOST=node_db1 
    restart: always
    depends_on:
      - node_db1
  
  node_db1:
    container_name: node_db1
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=node
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=0909
    volumes:
      - node_db1_data:/var/lib/postgresql/data

volumes:
  node_db1_data: {}



